apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  # https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  spawner_ui_config.yaml: |
    spawnerFormDefaults:
      image:
        value: ghcr.io/haoxins/jupyter-scipy:0.2.1
        options:
          - ghcr.io/haoxins/jupyter-scipy:0.2.1
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-scipy:v1.0.64
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-pytorch-full:v1.0.62
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-pytorch-full-cuda:v1.0.62
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-tensorflow-full:v1.0.22
          - ghcr.io/pluralsh/kubeflow-notebooks-jupyter-tensorflow-full-cuda:v1.0.22
      imageGroupOne:
        value: ""
        options:
      imageGroupTwo:
        value: ""
        options:
      allowCustomImage: true
      imagePullPolicy:
        value: IfNotPresent
        readOnly: false
      cpu:
        value: '1'
        limitFactor: "1.2"
        readOnly: false
      memory:
        value: 2.0Gi
        limitFactor: "1.2"
        readOnly: false
      environment:
        value: {}
        readOnly: false
      workspaceVolume:
        value:
          type:
            value: New
          name:
            value: 'workspace-{notebook-name}'
          size:
            value: '5Gi'
          mountPath:
            value: /home/jovyan
          accessModes:
            value: ReadWriteOnce
          class:
            value: '{none}'
        readOnly: false
      dataVolumes:
        value: []
        readOnly: false
      gpus:
        value:
          num: "none"
          vendors:
            - limitsKey: "nvidia.com/gpu"
              uiName: "NVIDIA"
            - limitsKey: "amd.com/gpu"
              uiName: "AMD"
          vendor: ""
        readOnly: false
      affinityConfig:
        value: ""
        options: []
      tolerationGroup:
        value: ""
        options: []
        readOnly: false
      shm:
        value: true
        readOnly: false
      configurations:
        value: []
    readOnly: false
