apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  # https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/jupyter/backend/apps/common/yaml/spawner_ui_config.yaml
  spawner_ui_config.yaml: |
    spawnerFormDefaults:
      image:
        value: ghcr.io/haoxins/jupyter-scipy:0.4.0
        options:
          - ghcr.io/haoxins/jupyter-scipy:0.4.0
          - ghcr.io/haoxins/jupyter-pytorch:0.4.0
          - ghcr.io/haoxins/jupyter-pytorch-cuda:0.4.0
      imageGroupOne:
        value: ""
        options:
      imageGroupTwo:
        value: ""
        options:
      allowCustomImage: true
      imagePullPolicy:
        value: IfNotPresent
        readOnly: false
      cpu:
        value: '1'
        limitFactor: "1.2"
        readOnly: false
      memory:
        value: 2.0Gi
        limitFactor: "1.2"
        readOnly: false
      environment:
        value: {}
        readOnly: false
      workspaceVolume:
        value:
          mount: /home/jovyan
          newPvc:
            metadata:
              name: "{notebook-name}-workspace"
            spec:
              resources:
                requests:
                  storage: 5Gi
              accessModes:
                - ReadWriteOnce
        readOnly: false
      dataVolumes:
        value: []
        readOnly: false
      gpus:
        value:
          num: "none"
          vendors:
            - limitsKey: "nvidia.com/gpu"
              uiName: "NVIDIA"
            - limitsKey: "amd.com/gpu"
              uiName: "AMD"
          vendor: ""
        readOnly: false
      affinityConfig:
        value: ""
        options: []
      tolerationGroup:
        value: ""
        options: []
        readOnly: false
      shm:
        value: true
        readOnly: false
      configurations:
        value: []
        readOnly: false
