# TODO: Use ExternalSecret with Google Cloud Secret Manager
apiVersion: v1
kind: Secret
metadata:
  name: git-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: <<__git_repo.url__>>
  username: <<__git_repo.username__>>
  password: <<__git_repo.password__>>
