# TODO: Use ExternalSecret with Google Cloud Secret Manager
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: <<__git_repo.url__>>
  password:
  username:
