apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/profile-controller/config/overlays/kubeflow?ref=1e9535ec06cae3823c33f29fc7890df9d32fcaf9 # tag=v1.4.0
