apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Uses the release branch instead of the tag because
# the image versions are pinned only in the release branch.
- https://github.com/kubeflow/katib/manifests/v1beta1/installs/katib-with-kubeflow?ref=release-0.13
