apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/katib/manifests/v1beta1/installs/katib-with-kubeflow?ref=v0.12.0

images:
- name: docker.io/kubeflowkatib/katib-controller
  newName: docker.io/kubeflowkatib/katib-controller
  newTag: v0.12.0
- name: docker.io/kubeflowkatib/katib-db-manager
  newName: docker.io/kubeflowkatib/katib-db-manager
  newTag: v0.12.0
- name: docker.io/kubeflowkatib/katib-ui
  newName: docker.io/kubeflowkatib/katib-ui
  newTag: v0.12.0
- name: mysql
  newName: mysql
  newTag: "8"
