apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/katib/manifests/v1beta1/installs/katib-with-kubeflow?ref=dfe8efec0ea2805b642ca331b3ca33f3aee4cd0a # tag=v0.12.0-rc.1

images:
- name: docker.io/kubeflowkatib/katib-controller
  newName: docker.io/kubeflowkatib/katib-controller
  newTag: v0.12.0-rc.0
- name: docker.io/kubeflowkatib/katib-db-manager
  newName: docker.io/kubeflowkatib/katib-db-manager
  newTag: v0.12.0-rc.0
- name: docker.io/kubeflowkatib/katib-ui
  newName: docker.io/kubeflowkatib/katib-ui
  newTag: v0.12.0-rc.0
- name: mysql
  newName: mysql
  newTag: "8"
