apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: default
  tag: 1.11.3
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    enablePrometheusMerge: true
    enableTracing: true
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
      tracing:
        sampling: 100.0
        max_path_tag_length: 256
        zipkin:
          address: jaeger-collector.istio-system.svc.cluster.local:9411
    extensionProviders:
    - name: oauth2-proxy
      envoyExtAuthzHttp:
        service: oauth2-proxy.auth.svc.cluster.local
        port: "4180"
        includeHeadersInCheck:
        - cookie
        - x-forwarded-access-token
        - x-forwarded-user
        - x-forwarded-email
        - authorization
        - x-forwarded-proto
        - proxy-authorization
        - user-agent
        - x-forwarded-host
        - from
        - x-forwarded-for
        - accept
        headersToUpstreamOnAllow:
        - authorization
        - path
        - x-auth-request-user
        - x-auth-request-email
        - x-auth-request-access-token
        - x-auth-request-user-groups
        headersToDownstreamOnDeny:
        - content-type
        - set-cookie
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        service:
          type: LoadBalancer
          externalTrafficPolicy: Local
    # Cluster-local gateway for KF Serving
    - enabled: true
      name: cluster-local-gateway
      label:
        app: cluster-local-gateway
        istio: cluster-local-gateway
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        hpaSpec:
          maxReplicas: 5
          metrics:
          - resource:
              name: cpu
              targetAverageUtilization: 80
            type: Resource
          minReplicas: 1
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: cluster-local-gateway
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        service:
          type: ClusterIP
          ports:
          - name: status-port
            port: 15020
            targetPort: 15020
          - name: http2
            port: 80
            targetPort: 8080
    # Disable EgressGateway
    egressGateways:
    - enabled: false
      name: istio-egressgateway
  values:
    global:
      tracer:
        zipkin:
          address: jaeger-collector.istio-system.svc.cluster.local:9411
      istiod:
        enableAnalysis: true
    sidecarInjectorWebhook:
      neverInjectSelector:
      # kube-prometheus-stack
      ## Admission Webhook jobs do not terminate as expected with istio-proxy
      - matchExpressions:
        - {key: app, operator: In, values: [kube-prometheus-stack-admission-create, kube-prometheus-stack-admission-patch, alertmanager]}
    pilot:
      autoscaleEnabled: true
      autoscaleMax: 5
      autoscaleMin: 1
      configMap: true
      cpu:
        targetAverageUtilization: 80
      env:
        PILOT_ENABLE_STATUS: true
